# simplify running the application with Docker Compose

version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    env_file:
      - .env